server:
  port: 7000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tutorial
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
application:
  version: 1.0-pre-release